# Generated by Django 4.0.1 on 2022-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_buyproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_place',
            name='status',
            field=models.CharField(default='Placed', max_length=100),
        ),
    ]
