# Generated by Django 4.0.1 on 2022-01-21 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_remove_product_discription'),
        ('app', '0003_alter_customuser_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('products', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='dash.product')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
