# Generated by Django 4.0.1 on 2022-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
