# Generated by Django 4.0.1 on 2022-01-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
