# Generated by Django 4.0.1 on 2022-02-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buyproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='user',
        ),
    ]
