# Generated by Django 4.0.1 on 2022-02-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_buyproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='guest',
            field=models.CharField(default='', max_length=300),
        ),
    ]
