# Generated by Django 4.0.1 on 2022-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_offer',
            field=models.IntegerField(default=0),
        ),
    ]
