# Generated by Django 4.0.1 on 2022-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cartproduct_price_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.EmailField(max_length=100),
        ),
    ]
