# Generated by Django 4.0.1 on 2022-02-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coupon_coupon_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_place',
            name='coupons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coupon'),
        ),
    ]
