# Generated by Django 4.0.1 on 2022-01-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_ads_homeimage1_ads_menimage1_ads_sportsimage1_and_more'),
        ('app', '0011_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='price',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
