# Generated by Django 4.0.1 on 2022-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_place_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_offer',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
