# Generated by Django 4.0.1 on 2022-02-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_coupon_coupon_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
