# Generated by Django 4.0.1 on 2022-02-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_coupon_coupon_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='guest',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
