# Generated by Django 4.0.1 on 2022-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cartproduct_guest_alter_cartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='Retotal',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
