# Generated by Django 4.0.1 on 2022-02-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cartproduct_retotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='Retotal',
        ),
    ]
