# Generated by Django 4.0.1 on 2022-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_wishlist_data_guest_alter_wishlist_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='alltotal',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
