# Generated by Django 2.2.12 on 2022-06-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeimage', models.ImageField(upload_to='')),
                ('homeimage1', models.ImageField(blank=True, upload_to='')),
                ('menimage', models.ImageField(upload_to='')),
                ('menimage1', models.ImageField(blank=True, upload_to='')),
                ('womenimage', models.ImageField(upload_to='')),
                ('womenimage1', models.ImageField(blank=True, upload_to='')),
                ('sportsimage', models.ImageField(upload_to='')),
                ('sportsimage1', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_offer', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('product_offer', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('image1', models.ImageField(upload_to='media/')),
                ('image2', models.ImageField(upload_to='media/')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Category')),
            ],
        ),
    ]
