# Generated by Django 4.0.1 on 2022-01-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_product_image1_product_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='imagea',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='imageb',
        ),
    ]
