# Generated by Django 4.0.1 on 2022-02-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
