# Generated by Django 4.0.1 on 2022-01-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_rename_image1_product_imagea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagea',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imageb',
            new_name='image2',
        ),
    ]
