# Generated by Django 4.0.1 on 2022-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_category_category_offer_product_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
