# Generated by Django 4.0.1 on 2022-01-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_rename_imagea_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
    ]
