# Generated by Django 4.0.1 on 2022-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_remove_product_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeimage', models.ImageField(upload_to='media/')),
                ('menimage', models.ImageField(upload_to='media/')),
                ('womenimage', models.ImageField(upload_to='media/')),
                ('sports', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
