# Generated by Django 4.0.1 on 2022-01-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='sports',
            new_name='sportsimage',
        ),
    ]
