# Generated by Django 4.0.1 on 2022-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_rename_sports_ads_sportsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='homeimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
