# Generated by Django 4.0.1 on 2022-01-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_alter_ads_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='homeimage1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ads',
            name='menimage1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ads',
            name='sportsimage1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ads',
            name='womenimage1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ads',
            name='menimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ads',
            name='sportsimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ads',
            name='womenimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
